version: '3.8'

services:
  # servidor de aplicação PHP;
  app:
    build:
      context: .
      dockerfile: ./docker-compose/app/Dockerfile
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/app/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db

  # Servidor web
  web:
    image: nginx:alpine
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app

  # Banco de dados
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
